apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "3434543"
  annotations:
    github.com/project-slug: ibrt2016/terraform-azure-web-mybob212 # Change the value to your github repo which contains terraform code.
    backstage.io/techdocs-ref: dir:.
  links:
  - url: https://github.com/claranet/terraform-azurerm-vnet
    title: 'VNet Terraform Module'
    icon: github
  tags:
    - azure
    - vnet
    - brand-new-deployment
    - high-criticality
    - ticket-number-3434543
    - entity-de
    - owner-bob-tayara
    - mybob212
    - prod
  title: 'Azure reource group and VNet - Ticket #3434543' # you can give any title
  description: |
   Azure reource group and VNet in stack `mybob212` in `prod` environment\
   \
   Ticket number: `3434543`\
   Details: Create `Azure VNet` and a `resource group` in a `brand new` stack `mybob212`, in `prod` environment and in `us-east` region\
   Action: Create a `new resource group` and a `new VNet`\
   Brand new deployment: `Yes`\
   VNet address space: `10.2.0.0/16`\
   VNet suffix: `001`\
   Stack name: `mybob212`\
   Stack owner: `Bob Tayara`\
   Azure subscription: `web`\
   Criticality: `High`\
   Entity: `DE`\
   Cost center: `00006` 
spec:
  type: service
  owner: user:guest
  lifecycle: experimental